Add string to numerical indexing TLB
csesoc/website pull request #174
Opened 2022-07-25 09:08 UTC by angary

- TODO: Implement cases for adding and removing keys

2022-07-25 10:41 UTC, Varun-Sethu approved these changes

2022-07-25 10:54 UTC, brianzhang2101 approved these changes
actually lgtm

2022-07-25 11:44 UTC, angary commented on Backend/editor/models/datamodel.go
> +	if d.tlb == nil {
so fax tell them king 👑

2022-07-25 12:43 UTC, Varun-Sethu commented on Backend/editor/models/datamodel.go
> +	if d.tlb == nil {
So true 🥺

2022-07-25 12:44 UTC, Varun-Sethu requested changes
I think this is inverted. Check discord for more details

2022-10-14 13:03 UTC, angary commented
Too old - will redo in future

2022-10-14 13:03 UTC, closed without merging