OT Frontend Changes - Stage 1
csesoc/website pull request #298
Opened 2022-10-31 12:25 UTC by Varun-Sethu

PR adds the first stage of the required changes to the front-end in order to support operational transform. This PR captures SlateJS operations and propagates them to a central place for delivery to the server. The PR after this will focus on translating SlateJS operations into the CMS operation format + sending them to the server and the final PR will focus on applying operations sent from the server to the editor.

2022-10-31 12:27 UTC, Varun-Sethu commented
Tests are failing because there appears to be something wrong with PIP implying the DB startup script couldn't be run and consequentially the backend testing env couldn't be created

2022-11-01 00:06 UTC, zijizhu approved these changes
Looks good to me!

2022-11-01 00:44 UTC, lauraw0 approved these changes
lgtm! :)

2022-11-01 10:09 UTC, lhjt requested changes

2022-11-01 10:09 UTC, lhjt commented on postgres/Dockerfile
> +FROM python:3.6-alpine
Any reason why it must be this old?

2022-11-02 09:27 UTC, Varun-Sethu commented on postgres/Dockerfile
> +FROM python:3.6-alpine
should be fixed now

2022-11-03 16:26 UTC, lhjt approved these changes

2022-11-03 23:58 UTC, merged