Multiapplication Support
csesoc/website pull request #359
Opened 2023-05-30 08:25 UTC by brianzhang2101

Schema redesign to allow other users besides the frontend team to get access to the CMS.

2023-07-06 07:19 UTC, Varun-Sethu requested changes
Looks good, some minor comments though and also:
 - Since I think the original goal of the ticket kinda changed its probs worth adding a full list of changes in the PR description
 - I think you may need to regenerate mocks as you did end up refactoring the repository layer quite a bit.
     - You will need to update https://github.com/csesoc/website/blob/3c8d63f5e6f408953dadf2961c7733744692d07b/backend/database/repositories/repository_interfaces.go#L3  to be `//go:generate mockgen -source=repository_interfaces.go -destination=mocks/repositories_mock.go -package=mocks`
     - And then run `go generate ./...` at the top level in the backend directory

2023-07-06 07:19 UTC, Varun-Sethu commented on backend/database/repositories/frontends.go
> +		return filesystemRepository{}, err
I feel like moving on there should be better handling of errors, perhaps we should wrap this error up in a secondary error to decorate it with a bit more context

2023-07-06 07:19 UTC, Varun-Sethu commented on backend/endpoints/dependency_factory.go
> +func (dp DependencyProvider) GetFilesystemRepo() (repos.FilesystemRepository, error) {
IMO the dependency provider should be decorating the error returned by the repository factory

2023-07-06 07:19 UTC, Varun-Sethu commented on backend/endpoints/filesystem_endpoints.go
> +			Status:   http.StatusNotFound,
I feel like this is an inappropriate response for failing to get the FS repo

2023-07-06 07:19 UTC, Varun-Sethu commented on backend/endpoints/filesystem_endpoints.go
> +			Status:   http.StatusNotFound,
Same here ^^

2023-07-08 04:25 UTC, Varun-Sethu requested changes

2023-07-08 04:25 UTC, Varun-Sethu commented on postgres/up/02-create_frontend_table.sql
> +  ID  uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
referencing discord discussion, so the FE ID is declared here

2023-07-08 04:25 UTC, Varun-Sethu commented on postgres/up/05-create_filesystem_table.sql
> +    RETURNING ID INTO frontendID;
then you create a new frontend here and take the frontend ID UUID

2023-07-08 04:25 UTC, Varun-Sethu commented on postgres/up/05-create_filesystem_table.sql
> +  INSERT INTO filesystem (EntityID, LogicalName, IsDocument, Parent, OwnedBy)
and then create a new file tree where the ID of the root is the frontendID, basically you overload the value you generate when creating a frontend to act as both the ID for the FE table and the ID for the root entity for that table

2023-07-08 04:25 UTC, Varun-Sethu commented on postgres/up/05-create_filesystem_table.sql
> +  INSERT INTO filesystem (EntityID, LogicalName, IsDocument, Parent, OwnedBy)
IMO u shouldn't do this, you should maintain a separate column within the FE table that references that root, additionally we should have a foreign key constraint somewhere that enforces that

2023-07-10 12:51 UTC, Varun-Sethu commented on backend/database/repositories/tests/filesystem_test.go
> +	repo, _             repositories.FilesystemRepository
no :(

2023-08-27 03:38 UTC, Varun-Sethu approved these changes

2023-08-31 04:08 UTC, ShunyaoLiang commented
Thanks for the meeting Brian. Looks great to me, just want there to be unit tests for multiple frontend repositories at once.

2023-09-03 04:25 UTC, brianzhang2101 commented
Luckily this test did actually spot a bug where `GetIDWithPath()` forgets to query specifically within the FE's filetree, thanks @ShunyaoLiang

2023-09-04 02:19 UTC, ShunyaoLiang approved these changes
That new test looks good to me. Great work Brian!

2023-09-04 02:22 UTC, merged